// gy-ufxgo.8 — capture the complete registry-v5 tuple at arrival.
//
// First touch wins for the funnel visit. The anonymous visitor ID persists
// across sessions; the funnel visit ID does not. Both are generated by the
// browser's cryptographic UUID implementation and revalidated before use.

import {
  ATTRIBUTION_SCHEMA_VERSION,
  normalizeAttributionPayload,
  resolveAttribution,
  visitId,
  type AttributionPayload,
} from "./sourceSlug.mjs";

const STORAGE_KEY = "gymbo.attribution.v2";
const VISITOR_KEY = "gymbo.anonymousVisitor.v1";
// State 3 (a signal that matched no registry entry) is remembered so first
// touch still wins: without it a later untagged page view would look like a
// measured no-signal visit and be stored as `unknown`.
const UNMATCHED_KEY = "gymbo.attribution.unmatched.v1";

type Stored = AttributionPayload & { at: string };

function readStore(): Stored | null {
  try {
    const raw = window.sessionStorage.getItem(STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const normalized = normalizeAttributionPayload(parsed);
    if (
      !normalized ||
      !normalized.funnel_visit_id ||
      !normalized.anonymous_visitor_id ||
      parsed.schema_version !== ATTRIBUTION_SCHEMA_VERSION ||
      typeof parsed.at !== "string"
    ) {
      return null;
    }
    return { ...normalized, at: parsed.at };
  } catch {
    return null;
  }
}

function hasUnmatchedMarker(): boolean {
  try {
    return window.sessionStorage.getItem(UNMATCHED_KEY) !== null;
  } catch {
    return false;
  }
}

function writeUnmatchedMarker(): void {
  try {
    window.sessionStorage.setItem(UNMATCHED_KEY, new Date().toISOString());
  } catch {
    /* Storage can be unavailable in privacy modes; never break the form. */
  }
}

function writeStore(value: Stored): void {
  try {
    window.sessionStorage.setItem(STORAGE_KEY, JSON.stringify(value));
  } catch {
    /* Storage can be unavailable in privacy modes; never break the form. */
  }
}

function newVisitId(): string | null {
  try {
    return visitId(window.crypto.randomUUID());
  } catch {
    return null;
  }
}

function anonymousVisitorId(): string | null {
  try {
    const existing = visitId(window.localStorage.getItem(VISITOR_KEY));
    if (existing) return existing;
    const created = newVisitId();
    if (created) window.localStorage.setItem(VISITOR_KEY, created);
    return created;
  } catch {
    return newVisitId();
  }
}

/** Record the complete acquisition tuple for this session exactly once. */
export function captureAttribution(): void {
  if (typeof window === "undefined" || readStore() || hasUnmatchedMarker()) return;

  let params = new URLSearchParams();
  try {
    params = new URLSearchParams(window.location.search);
  } catch {
    // A malformed location is handled as an unattributed measured arrival.
  }

  const tuple = resolveAttribution({
    utmSource: params.get("utm_source"),
    utmMedium: params.get("utm_medium"),
    utmCampaign: params.get("utm_campaign"),
    referrer: typeof document !== "undefined" ? document.referrer : null,
    selfHost: window.location.hostname,
  });
  // A signal that matches no registry entry sends NO attribution (never
  // `unknown`, never the raw value). The server stores it as all-NULL.
  if (!tuple) {
    writeUnmatchedMarker();
    return;
  }

  const funnelVisitId = newVisitId();
  const visitorId = anonymousVisitorId();

  // Never substitute a weak/decorative identifier if secure UUID generation is
  // unavailable. A later load can retry; the form remains usable meanwhile.
  if (!funnelVisitId || !visitorId) return;

  writeStore({
    ...tuple,
    funnel_visit_id: funnelVisitId,
    anonymous_visitor_id: visitorId,
    schema_version: ATTRIBUTION_SCHEMA_VERSION,
    at: new Date().toISOString(),
  });
}

/**
 * The complete revalidated payload to send with a lead, or null when there is
 * nothing to send: uncaptured, or a signal that matched no registry entry.
 */
export function getAttribution(): AttributionPayload | null {
  if (typeof window === "undefined") return null;
  const stored = readStore();
  if (!stored) return null;
  const { at: _at, ...payload } = stored;
  return payload;
}

/** Source-only compatibility API for callers that have not moved to the tuple. */
export function getAttributionSource(): string | null {
  return getAttribution()?.source ?? null;
}
